name: CI/CD Pipeline for React App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          BRANCH: gh-pages
          FOLDER: build  